[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["chmod +x build.sh", "./build.sh"]

[start]
cmd = "java -Xmx512m -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/lat-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_VERSION = "17"
MAVEN_ARGS = "-DskipTests"
