[phases.setup]
nixPkgs = ["openjdk17"]

[phases.build]
cmds = ["mvn clean package -DskipTests -Dmaven.compiler.source=17 -Dmaven.compiler.target=17"]

[start]
cmd = "java -Xmx512m -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/lat-0.0.1-SNAPSHOT.jar"

[variables]
JAVA_VERSION = "17"